config/routes.rb
Rails.application.routes.draw do

  root "home#index"
  get "/buildings", to:"buildings#index", defaults: { building_type:'building', min_max_level:'1'} 
  get "/units", to:"buildings#index", defaults: { building_type:'unit', min_max_level:'2'}
  get "/spells", to: "buildings#index", defaults: { building_type:'spell', min_max_level:'2'}

  resources :available_upgrades
  resources :builders
  resources :buildings
  resources :dashboards
  resources :home 
  resources :maxed_townhalls
  resources :townhalls
  resources :walls

  # this is where we update the game information when it is updated
  namespace :admin do
    resources :building_availabilities
    resources :building_basic_infos
    resources :building_cost_infos
    resources :building_max_levels
    resources :wall_availabilities
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
end

app/models/building_max_level.rb
class BuildingMaxLevel < ActiveRecord::Base
end

app/controllers/admin/building_max_levels_controller.rb
class Admin::BuildingMaxLevelsController < ApplicationController
  layout 'admin_sidenav'
  load_and_authorize_resource
  before_action :set_building_max_level, only: [:show, :edit, :update, :destroy]

  def new
    @building_max_level = BuildingMaxLevel.new
  end

  def create
    @building_max_level = BuildingMaxLevel.new(building_max_level_params)
    if @building_max_level.save
      redirect_to(admin_building_max_level_path(@building_max_level), notice: "Building max level created")
    end
  end

  def index
    @building_max_levels = BuildingMaxLevel.all
  end

  def show

  end

  def edit

  end

  def update
    @building_max_level.update(building_max_level_params)
    redirect_to(admin_building_max_level_path(@building_max_level), notice: "Building Max Level Updated")
  end

  def destroy
    @building_max_levels.destroy
    redirect_to(admin_building_max_levels_path, notice: "Building Max Level DESTROYYYYD")
  end


  private
  def building_max_level_params
    params.require(:building_max_level).permit(:name, :level, :max_level)
  end

  def set_building_max_level
    @building_max_level = BuildingMaxLevel.find(params[:id])
  end

end

app/helpers/building_max_levels_helper.rb
module BuildingMaxLevelsHelper
end

app/views/admin/building_max_levels/_form.html.haml
= form_for([:admin, @building_max_level], html: { class: 'form-horizontal' }) do |f|
  = f.error_notification

  .form-inputs
    = f.form_group :name do |f|
      = f.label :name, class: 'control-label col-md-2'
      .col-md-8
        = f.text_field :name, class: 'form-control'
        = f.error_messages
    = f.form_group :townhall_level do |f|
      = f.label :townhall_level, class: 'control-label col-md-2'
      .col-md-8
        = f.number_field :townhall_level, class: 'form-control'
        = f.error_messages
    = f.form_group :max_level do |f|
      = f.label :max_level, class: 'control-label col-md-2'
      .col-md-8
        = f.number_field :max_level, class: 'form-control'
        = f.error_messages

  .form-actions.col-md-offset-3.col-md-9
    = f.submit class: 'btn btn-primary'
    = link_to "Cancel", admin_building_max_levels_path, class: 'btn'

app/views/admin/building_max_levels/edit.html.haml
- @title = "Editing building_max_level"

.container
  .row
    .col-xs-12.col-sm-12.col-md-12.col-lg-12
      = render 'form'

app/views/admin/building_max_levels/index.html.haml
- @title = "Listing building_max_levels"

- content_for :description do
  %p Edit this template in app/views/BuildingMaxLevels/index.html.haml.

- content_for :actions do
  = link_to new_admin_building_max_level_path, class: 'btn btn-primary btn-large pull-right' do
    = fa_icon_tag "plus"
    Add Building max level

.container
  .row
    .col-xs-12.col-sm-12.col-md-12.col-lg-12
      .sheet.sheet-condensed
        .sheet-inner
          %table.table
            %thead
              %tr
                %th Name
                %th Townhall level
                %th Max level
                %th
            %tbody
            - @building_max_levels.each do |building_max_level|
              %tr
              %td= building_max_level.name
              %td= building_max_level.townhall_level
              %td= building_max_level.max_level
              %td
                = link_to(fa_icon_tag("eye"), admin_building_max_level_path(building_max_level), rel: 'tooltip', title: 'Show')
                = link_to fa_icon_tag("pencil"), edit_admin_building_max_level_path(building_max_level), rel: 'tooltip', title: 'Edit'
                = link_to fa_icon_tag("trash"), admin_building_max_level_path(building_max_level), rel: 'tooltip', title: 'Delete', data: { confirm: 'Are you sure?' }, method: :delete

            

app/views/admin/building_max_levels/new.html.haml
- @title = "New building_max_level"

.container
  .row
    .col-xs-12.col-sm-12.col-md-12.col-lg-12
      = render 'form'

app/views/admin/building_max_levels/show.html.haml
- @title = "Showing building_max_level"

.container
  .row
    .col-xs-12.col-sm-12.col-md-12.col-lg-12
      .form-horizontal
        .form-group
          %label.col-sm-2.form-label Name
          .uneditable-input.col-md-8.form-control
            %span= @building_max_level.name

        .form-group
          %label.col-sm-2.form-label Townhall level
          .uneditable-input.col-md-8.form-control
            %span= @building_max_level.townhall_level

        .form-group
          %label.col-sm-2.form-label Max level
          .uneditable-input.col-md-8.form-control
            %span= @building_max_level.max_level

        .form-actions.col-md-offset-2
          = link_to fa_icon_tag("pencil") + ' Edit', edit_admin_building_max_level_path(@building_max_level), class: 'btn btn-primary'
          = link_to 'Back', admin_building_max_levels_path, class: 'btn'