config/routes.rb
Rails.application.routes.draw do

  root "home#index"
  get "/buildings", to:"buildings#index", defaults: { building_type:'building', min_max_level:'1'} 
  get "/units", to:"buildings#index", defaults: { building_type:'unit', min_max_level:'2'}
  get "/spells", to: "buildings#index", defaults: { building_type:'spell', min_max_level:'2'}

  resources :available_upgrades
  resources :builders
  resources :buildings
  resources :dashboards
  resources :home 
  resources :maxed_townhalls
  resources :townhalls
  resources :walls

  # this is where we update the game information when it is updated
  namespace :admin do
    resources :building_availabilities
    resources :building_basic_infos
    resources :building_cost_infos
    resources :building_max_levels
    resources :wall_availabilities
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
end

app/models/building_availability.rb
class BuildingAvailability < ActiveRecord::Base
    has_many :buildings, primary_key: "unique_building_code", foreign_key: "unique_building_code"
    belongs_to :building_basic_info, primary_key: "name", foreign_key: "name"
    
end

app/controllers/admin/building_availabilities_controller.rb
class Admin::BuildingAvailabilitiesController < ApplicationController
  layout 'admin_sidenav'
  load_and_authorize_resource
  before_action :set_building_availability, only: [:show, :edit, :update, :destroy]

  def new
    @building_availability = BuildingAvailability.new
  end

  def create
    @building_availability = BuildingAvailability.new(building_availability_params)
    if @building_availability.save
      redirect_to(admin_building_availability_path(@building_availability), notice: "Successfully created Building Availability")
    end
  end

  def show
  end

  def index
    @building_availability = BuildingAvailability.all
  end

  def edit 
  end

  def update
    @building_availability.update(building_availability_params)
    redirect_to(admin_building_availability_path(@building_availability), notice: "Building Availability... UPDATED!")
  end

  def destroy
    @building_availability.destroy
    redirect_to(admin_building_availabilities_path, notice: "Building Availability... DESTROYED!")
  end

  private
  def building_availability_params
    params.require(:building_availability).permit(:unique_building_code, :active_on, :name)
  end


  def set_building_availability
    @building_availability = BuildingAvailability.find(params[:id])
  end

end

app/views/admin/building_availabilities/_form.html.haml
= form_for([:admin, @building_availability], html: { class: "form-horizontal"}) do |f|
  = f.label(:name)
  = f.text_field(:name)

  = f.label(:unique_building_code)
  = f.text_field(:unique_building_code)

  = f.label(:active_on)
  = f.number_field(:active_on)

  = f.submit

app/views/admin/building_availabilities/index.html.haml
%br
Every Building that gets add to clash needs an entry
%br
(ie -> th 8 3 mortars to 4 mortars)
%br
That 4th mortar needs a building_availability_entry
%br
Create New Building Availability
= link_to("New Building Availability", new_admin_building_availability_path)
%br
%table
  %tr
    %th
      id
    %th
      Name
    %th
      Unique Building Code
    %th
      Active On
    %th
      Show
    %th
      Edit
    %th
      Destroy!
  - @building_availability.each do |ba|
    %tr
      %td
        = ba.id
      %td
        = ba.name
      %td
        = ba.unique_building_code
      %td
        = ba.active_on
      %td
        = link_to("Show", admin_building_availability_path(ba))
      %td
        = link_to("Edit",edit_admin_building_availability_path(ba))
      %td
        = link_to("Destroy", admin_building_availability_path(ba), method: :delete, data: { confirm: "You sure dawg?" })

app/views/admin/building_availabilities/show.html.haml
%br 
id: #{ @building_availability.id }
%br
Name: #{ @building_availability.name }
%br
Unique Building Code:  #{ @building_availability.unique_building_code }
%br
TH Level Availabile On: #{ @building_availability.active_on }
%br
= link_to("Back", admin_building_availabilities_path)
%br
= link_to("Edit", edit_admin_building_availability_path(@building_availability))