config/routes.rb
Rails.application.routes.draw do

  root "home#index"
  get "/buildings", to:"buildings#index", defaults: { building_type:'building', min_max_level:'1'} 
  get "/units", to:"buildings#index", defaults: { building_type:'unit', min_max_level:'2'}
  get "/spells", to: "buildings#index", defaults: { building_type:'spell', min_max_level:'2'}

  resources :available_upgrades
  resources :builders
  resources :buildings
  resources :dashboards
  resources :home 
  resources :maxed_townhalls
  resources :townhalls
  resources :walls

  # this is where we update the game information when it is updated
  namespace :admin do
    resources :building_availabilities
    resources :building_basic_infos
    resources :building_cost_infos
    resources :building_max_levels
    resources :wall_availabilities
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
end

app/models/building_cost_info.rb
class BuildingCostInfo < ActiveRecord::Base
  self.primary_keys = :name, :level
  has_many :buildings, foreign_key: [:name, :level]
  has_many :walls, foreign_key: [:name, :level]
  before_save :set_cumulative_cost

  def image_url
    "/assets/#{self.name}#{self.level}.png"
  end

  private
  def set_cumulative_cost
    cumulative_cost = BuildingCostInfo.where('name = ? AND level < ?', self.name, self.level).sum(:cost)
    cumulative_time = BuildingCostInfo.where('name = ? AND level < ?', self.name, self.level).sum(:time)
    self.cumulative_cost = self.cost + cumulative_cost
    self.cumulative_time = self.time + cumulative_time
  end
  # we need to update cumulative cost and things when we create, update, and whatnot
end

app/controllers/admin/building_cost_infos_controller.rb
class Admin::BuildingCostInfosController < ApplicationController
  layout 'admin_sidenav'
  load_and_authorize_resource
  before_action :set_building_cost_info, only: [:show, :edit, :update, :destroy]

  def new
    @building_cost_info = BuildingCostInfo.new
  end

  def create
    @building_cost_info = BuildingCostInfo.new(building_cost_info_params)
    if @building_cost_info.save
      redirect_to(admin_building_cost_info_path(@building_cost_info), notice: "Building Cost Info Successfully CREATED!")
    end
  end

  def index
    @building_cost_info = BuildingCostInfo.all
  end

  def show

  end

  def edit

  end

  def update
    @building_cost_info.update(building_cost_info_params)
    redirect_to(admin_building_cost_info_path(@building_cost_info), notice: "Building Cost Info Updated!")
  end

  def destroy
    @building_cost_info.destroy
    redirect_to(admin_building_cost_infos_path, notice: "DESTROYED!!!! No going back.")
  end

  private
  def building_cost_info_params
    params.require(:building_cost_info).permit(:name, :level, :upgrade_resource, :cost, :time, :training_cost, :training_resource, :production_amount, :production_resource)
  end

  def set_building_cost_info
    @building_cost_info = BuildingCostInfo.find(params[:id])
  end

end

app/views/admin/building_cost_infos/_form.html.haml
= form_for([:admin, @building_cost_info], html: { class:"form-horizontal"}) do |f|
  = f.label(:name)
  = f.text_field(:name)
  %br
  = f.label(:level)
  = f.number_field(:level)
  %br
  = f.label(:upgrade_resource)
  = f.text_field(:upgrade_resource)
  %br
  = f.label(:cost)
  = f.number_field(:cost)
  %br
  = f.label(:time)
  = f.number_field(:time)
  %br
  = f.label(:training_cost)
  = f.number_field(:training_cost)
  %br
  = f.label(:training_resource)
  = f.text_field(:training_resource)
  %br
  = f.label(:production_amount)
  = f.number_field(:production_amount)
  %br
  = f.label(:production_resource)
  = f.text_field(:production_resource)
  %br
  = f.submit

app/views/admin/building_cost_infos/edit.html.haml
= render 'form'

app/views/admin/building_cost_infos/index.html.haml
%h2 
  = link_to("Create New Building Cost Info", new_admin_building_cost_info_path)

%table
  %thead
    %tr
      %th
        Name
      %th
        Level
      %th
        Upgrade Resource
      %th
        Cost
      %th
        Cumulative Cost
      %th
        Time
      %th
        Cumulative Time
      %th
        Training Cost
      %th
        Training Resource
      %th
        Production Amount
      %th
        Production Resource
      %th
        Show
      %th
        Edit
      %th
        DESTROY!
  %tbody
    - @building_cost_info.each do |bci|
      %tr
        %td
          =  bci.name
        %td
          =  bci.level
        %td
          =  bci.upgrade_resource
        %td
          = bci.cost
        %td
          = bci.cumulative_cost
        %td
          =  bci.time
        %td
          = bci.cumulative_time
        %td
          =  bci.training_cost
        %td
          =  bci.training_resource
        %td
          =  bci.production_amount
        %td
          =  bci.production_resource
        %td
          = link_to("Show", admin_building_cost_info_path(bci))
        %td
          = link_to("Edit", edit_admin_building_cost_info_path(bci))
        %td
          = link_to("Destroy", admin_building_cost_info_path(bci), method: "delete", data: { confirm: "You sure dawg?" })

app/views/admin/building_cost_infos/new.html.haml
= render 'form'

app/views/admin/building_cost_infos/show.html.haml
%br
  Name: #{ @building_cost_info.name }
%br
  Level: #{ @building_cost_info.level }
%br
  Upgrade Resource: #{ @building_cost_info.upgrade_resource }
%br
  Cost: #{ @building_cost_info.cost }
%br
  Time: #{ @building_cost_info.time }
%br
  Cumulative Cost: #{ @building_cost_info.cumulative_cost }
%br
  Cumulative Time: #{ @building_cost_info.cumulative_time }
%br
  Training Cost: #{ @building_cost_info.training_cost }
%br
  Training Resource: #{ @building_cost_info.training_resource }
%br
  Production Amount: #{ @building_cost_info.production_amount }
%br
  Production Resource: #{ @building_cost_info.production_resource }
%br
  = link_to("Back", admin_building_cost_infos_path)
%br
  = link_to("Edit", edit_admin_building_cost_info_path)